/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#131315",
        surface: {
          950: "#0e0e10",
          900: "#1b1b1d",
          800: "#1f1f21",
          700: "#2a2a2c",
          DEFAULT: "#131315",
        },
        accent: {
          400: "#6ffbbe",
          500: "#4edea3",
          600: "#00a572",
        },
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c4c7c8",
        "on-secondary": "#003824",
        "secondary": "#4edea3",
        "secondary-container": "#00a572",
        "surface-container": "#1f1f21",
        "surface-container-low": "#1c1b1d",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-container-lowest": "#0e0e10",
        "surface-variant": "#353437",
        "on-secondary-container": "#00616d",
        "on-secondary-fixed": "#001f24",
        "on-secondary-fixed-variant": "#004f58",
        "on-primary": "#2f3131",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",
        "surface-bright": "#39393b",
        outline: "#8e9192",
        "outline-variant": "#444748",
        error: "#ffb4ab",
        "error-container": "#93000a",
        primary: "#ffffff",
        tertiary: "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-page": "48px",
        base: "4px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        mono: ["IBM Plex Mono", "SFMono-Regular", "Consolas", "Liberation Mono", "monospace"],
        "headline-md": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "headline-lg": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "headline-lg-mobile": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "display-xl": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "title-md": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "label-sm": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "label-caps": ["IBM Plex Mono", "SFMono-Regular", "Consolas", "Liberation Mono", "monospace"],
        "code-md": ["IBM Plex Mono", "SFMono-Regular", "Consolas", "Liberation Mono", "monospace"],
        "body-md": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "body-lg": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "body-base": ["Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        "code-sm": ["IBM Plex Mono", "SFMono-Regular", "Consolas", "Liberation Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "650" }],
        "headline-lg": ["34px", { lineHeight: "1.18", letterSpacing: "0", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-base": ["14px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      boxShadow: {
        glow: "0 0 0 1px rgba(78,222,163,0.12), 0 22px 50px rgba(0,0,0,0.36)",
      },
      backgroundImage: {
        grid: "radial-gradient(circle at 1px 1px, rgba(148,163,184,0.14) 1px, transparent 0)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-6px)" },
        },
      },
      animation: {
        float: "float 7s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
