export const SEED_JOBS = [
  {
    id: "job-001",
    title: "Senior Frontend Engineer",
    company: "Northwind Labs",
    location: "Bengaluru, India",
    workMode: "hybrid",
    salaryBand: "₹28–40 LPA",
    skills: ["TypeScript", "React", "Next.js", "GraphQL", "Web performance"],
    summary: "Own design-system-driven UI for a B2B analytics platform.",
  },
  {
    id: "job-002",
    title: "Full Stack Engineer",
    company: "BlueCanopy",
    location: "Remote",
    workMode: "remote",
    salaryBand: "$120k–155k USD",
    skills: ["Node.js", "PostgreSQL", "React", "AWS", "REST APIs"],
    summary: "Ship customer-facing workflows with strong API design ownership.",
  },
  {
    id: "job-003",
    title: "Backend Engineer — Payments",
    company: "Paystream",
    location: "Singapore",
    workMode: "onsite",
    salaryBand: "S$100k–140k",
    skills: ["Java", "Kafka", "Redis", "Distributed systems", "Security"],
    summary: "Build resilient payment orchestration services at scale.",
  },
  {
    id: "job-004",
    title: "ML Engineer",
    company: "Helio AI",
    location: "Remote (EU)",
    workMode: "remote",
    salaryBand: "€80k–110k",
    skills: ["Python", "PyTorch", "LLMs", "MLOps", "Data pipelines"],
    summary: "Fine-tune and evaluate domain-specific language models.",
  },
  {
    id: "job-005",
    title: "Product Engineer",
    company: "Craftboard",
    location: "Hyderabad, India",
    workMode: "hybrid",
    salaryBand: "₹22–32 LPA",
    skills: ["React", "Product sense", "SQL", "A/B testing", "TypeScript"],
    summary: "Partner with PM and design to run rapid product experiments.",
  },
  {
    id: "job-006",
    title: "DevOps Engineer",
    company: "Gridline Cloud",
    location: "Pune, India",
    workMode: "hybrid",
    salaryBand: "₹18–28 LPA",
    skills: ["Kubernetes", "Terraform", "CI/CD", "AWS", "Observability"],
    summary: "Harden multi-tenant SaaS infrastructure and deployment pipelines.",
  },
  {
    id: "job-007",
    title: "Mobile Engineer (React Native)",
    company: "Orbit Health",
    location: "Remote",
    workMode: "remote",
    salaryBand: "$110k–145k USD",
    skills: ["React Native", "TypeScript", "Health APIs", "Offline-first UX"],
    summary: "Improve patient engagement apps used in 40+ markets.",
  },
  {
    id: "job-008",
    title: "Data Engineer",
    company: "Silverline Analytics",
    location: "Chennai, India",
    workMode: "onsite",
    salaryBand: "₹16–24 LPA",
    skills: ["Python", "dbt", "Snowflake", "Airflow", "SQL"],
    summary: "Model trusted metrics for revenue and operations teams.",
  },
  {
    id: "job-009",
    title: "Security Engineer",
    company: "FortMesh",
    location: "Remote",
    workMode: "remote",
    salaryBand: "$130k–175k USD",
    skills: ["AppSec", "Threat modeling", "AWS", "Python", "SOC2"],
    summary: "Lead secure SDLC practices for a compliance-heavy SaaS product.",
  },
  {
    id: "job-010",
    title: "Engineering Manager",
    company: "Atlas Commerce",
    location: "London, UK",
    workMode: "hybrid",
    salaryBand: "£95k–125k",
    skills: ["People leadership", "Java", "Cloud architecture", "Hiring"],
    summary: "Grow a platform team building global checkout experiences.",
  },
];
